"""Transactional startup migrations with database-only recovery snapshots.

User originals, blobs and attachments stay at their existing paths. Snapshots are
never restored automatically: restoring one would discard later user edits.
"""
from __future__ import annotations

import contextlib
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import sqlite3
import uuid

from .runtime import OwnerLock
from .schemas import BusinessError

VERSION_KEY = 'framework_version'
STATUS_FILE = 'upgrade-state.json'
BACKUP_DIR = 'upgrade-backups'


def _now():
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec='milliseconds')


def _version(value):
    if not isinstance(value, str) or not re.fullmatch(r'\d+\.\d+\.\d+', value):
        raise BusinessError('upgrade_version', '无法确认此数据空间的软件版本；为保护资料，已停止启动。')
    return tuple(int(part) for part in value.split('.'))


def _plain(path):
    """Do not send automatic recovery files through a user-created junction."""
    if path.is_symlink() or getattr(path, 'is_junction', lambda: False)():
        raise BusinessError('upgrade_path', '升级保护目录不能是符号链接或目录联接；原资料未修改。')
    return path


def _json_write(path, value):
    _plain(path)
    temporary = path.with_name(path.name + '.' + uuid.uuid4().hex + '.partial')
    try:
        with temporary.open('x', encoding='utf-8') as stream:
            json.dump(value, stream, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _read_status(root):
    path = _plain(root / STATUS_FILE)
    if not path.exists():
        return None
    try:
        value = json.loads(path.read_text(encoding='utf-8'))
        if (not isinstance(value, dict) or value.get('format') != 'personal-management-upgrade/1'
                or value.get('status') not in {'prepared', 'completed', 'failed'}):
            raise ValueError()
        _version(value.get('to_version'))
        return value
    except (ValueError, OSError) as exc:
        raise BusinessError('upgrade_record', '升级保护记录无法读取；原资料已保留，请修复记录后再启动。') from exc


def _digest(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def _database_check(connection):
    if connection.execute('PRAGMA quick_check').fetchall() != [('ok',)]:
        raise BusinessError('upgrade_database_check', '数据库完整性检查未通过；已停止升级，未替换原资料。')
    if connection.execute('PRAGMA foreign_key_check').fetchone():
        raise BusinessError('upgrade_database_check', '数据库关联检查未通过；已停止升级，未替换原资料。')


def _snapshot(root, previous, current):
    directory = _plain(root / BACKUP_DIR)
    attempt = directory / (dt.datetime.now().strftime('%Y%m%d-%H%M%S-') + uuid.uuid4().hex)
    partial = attempt / 'database.sqlite3.partial'
    final = attempt / 'database.sqlite3'
    # SQLite's online backup includes committed WAL contents. The caller holds
    # BEGIN IMMEDIATE on another connection, excluding writers until migration.
    try:
        directory.mkdir(exist_ok=True)
        attempt.mkdir()
        with contextlib.closing(sqlite3.connect((root / 'database.sqlite3').as_uri() + '?mode=ro', uri=True)) as source:
            with contextlib.closing(sqlite3.connect(partial)) as destination:
                source.backup(destination, pages=256, sleep=0.05)
                _database_check(destination)
        with partial.open('r+b') as stream:
            os.fsync(stream.fileno())
        os.replace(partial, final)
        record = {'format': 'personal-management-upgrade/1', 'status': 'prepared',
                  'from_version': previous, 'to_version': current, 'created_at': _now(),
                  'backup_scope': 'database_only', 'assets': 'retained_at_original_paths',
                  'data_dir': str(root), 'snapshot': str(final.relative_to(root)),
                  'snapshot_bytes': final.stat().st_size, 'snapshot_sha256': _digest(final),
                  'snapshot_check': 'quick_check_and_foreign_keys'}
        _json_write(attempt / 'upgrade.json', record)
        _json_write(root / STATUS_FILE, record)
        return record
    except (OSError, sqlite3.Error) as exc:
        raise BusinessError('upgrade_backup_failed', '无法完成升级前的数据库快照（可能空间不足或无写入权限）；原资料未迁移。') from exc


def _record(root, record, status):
    updated = {**record, 'status': status, 'updated_at': _now()}
    # The relative path was generated by this module, but a persisted record is
    # untrusted. Never allow a damaged record to write outside the backup tree.
    value = record.get('snapshot')
    if not isinstance(value, str):
        raise BusinessError('upgrade_record', '升级快照位置无效；未执行恢复或覆盖。')
    relative = Path(value)
    if (relative.is_absolute() or '..' in relative.parts or len(relative.parts) != 3
            or relative.parts[0] != BACKUP_DIR or relative.name != 'database.sqlite3'):
        raise BusinessError('upgrade_record', '升级快照位置无效；未执行恢复或覆盖。')
    directory = _plain(_plain(root / BACKUP_DIR) / relative.parts[1])
    snapshot = _plain(directory / relative.name)
    if (not snapshot.is_file() or snapshot.stat().st_size != record.get('snapshot_bytes')
            or _digest(snapshot) != record.get('snapshot_sha256')):
        raise BusinessError('upgrade_snapshot_changed', '升级保护快照缺失或已变化；已保留当前资料，请先核对升级记录。')
    _json_write(directory / 'upgrade.json', updated)
    _json_write(root / STATUS_FILE, updated)
    return updated


class _StartupConnection(sqlite3.Connection):
    def executescript(self, script):
        """sqlite3.executescript commits implicitly; startup must stay atomic."""
        pending = ''
        cursor = None
        for char in script:
            pending += char
            if char == ';' and sqlite3.complete_statement(pending):
                cursor = self.execute(pending)
                pending = ''
        if pending.strip():
            cursor = self.execute(pending)
        return cursor


@contextlib.contextmanager
def schema_upgrade(root):
    from . import __version__
    root = Path(root).resolve()
    current = __version__
    _version(current)
    # Reject unrelated/future-schema files before creating even our lock file.
    # Repeat these checks inside the transaction below to close the race.
    path = root / 'database.sqlite3'
    if path.exists() and path.stat().st_size:
        with contextlib.closing(sqlite3.connect(path.as_uri() + '?mode=ro', uri=True)) as probe:
            if not probe.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='meta'").fetchone():
                raise BusinessError('unknown_database', '此文件不是软件创建的数据空间，未修改。')
            row = probe.execute("SELECT value FROM meta WHERE key='schema_version'").fetchone()
            if not row or json.loads(row[0]) != 1:
                raise BusinessError('schema_version', '此数据空间需要不同版本的软件；未改动业务数据。')
    lock = OwnerLock(_plain(root / 'schema-upgrade.lock'))
    if not lock.acquire():
        raise BusinessError('upgrade_busy', '此数据空间正在检查或升级，请稍后重新打开。')
    connection = None
    record = None
    committed = False
    try:
        path = root / 'database.sqlite3'
        existing = path.exists() and path.stat().st_size > 0
        connection = sqlite3.connect(path, timeout=5, isolation_level=None, factory=_StartupConnection)
        connection.execute('PRAGMA foreign_keys=ON')
        connection.execute('PRAGMA busy_timeout=5000')
        connection.execute('PRAGMA synchronous=FULL')
        connection.execute('BEGIN IMMEDIATE')
        previous = None
        if existing:
            if not connection.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='meta'").fetchone():
                raise BusinessError('unknown_database', '此文件不是软件创建的数据空间，未修改。')
            row = connection.execute("SELECT value FROM meta WHERE key='schema_version'").fetchone()
            if not row or json.loads(row[0]) != 1:
                raise BusinessError('schema_version', '此数据空间需要不同版本的软件；未改动业务数据。')
            row = connection.execute('SELECT value FROM meta WHERE key=?', (VERSION_KEY,)).fetchone()
            previous = json.loads(row[0]) if row else None
            if previous is not None and _version(previous) > _version(current):
                raise BusinessError('upgrade_downgrade', '此数据空间已由较新版软件升级。请安装相同或更新版本；未降级或覆盖资料。',
                                    {'data_version': previous, 'application_version': current})
        status = _read_status(root)
        if status and status['status'] == 'prepared' and previous == status['to_version']:
            # Commit was durable but the process ended before completing its
            # external receipt. The DB marker, not JSON, proves success.
            _record(root, status, 'completed')
        if existing and previous != current:
            record = _snapshot(root, previous, current)
        connection.row_factory = sqlite3.Row
        yield connection
        connection.execute('INSERT INTO meta(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',
                           (VERSION_KEY, json.dumps(current)))
        if not existing or previous != current:
            connection.row_factory = None
            _database_check(connection)
            connection.row_factory = sqlite3.Row
        connection.commit()
        committed = True
        if record:
            _record(root, record, 'completed')
        connection.execute('PRAGMA journal_mode=WAL')
    except BaseException:
        if connection is not None and not committed:
            connection.rollback()
        if record and not committed:
            # Reporting errors must not replace the original migration error.
            with contextlib.suppress(OSError, BusinessError):
                _record(root, record, 'failed')
        raise
    finally:
        if connection is not None:
            connection.close()
        lock.release()
